#!/bin/bash
# find-in-file - usage: fif <searchTerm>
# https://github.com/junegunn/fzf/wiki/examples#searching-file-contents
set -euo pipefail

if [ ! "$#" -gt 0 ]; then
    echo "Need a string to search for!";
    exit 1;
fi
# using ripgrep combined with preview
rg --files-with-matches --no-messages "$1" | fzf --preview "highlight -O ansi -l {} 2> /dev/null | rg --colors 'match:bg:yellow' --ignore-case --pretty --context 10 '$1' || rg --ignore-case --pretty --context 10 '$1' {}"
