#!/usr/bin/bash
echo https://truveris.github.io/articles/configuring-pypirc/
echo python setup.py sdist bdist_wheel
echo pip install twine
echo twine upload -r testpypi dist/\*
echo twine upload dist/\*
