#! /usr/bin/bash
logs=${HOME}/.logs
if [ -d ${logs} ]
then
    currdate=`/usr/bin/date +%d%m%Y`
    file=/tmp/${currdate}-timesheet.csv
    to="salah93@crosscompute.com"
    source ${HOME}/.apis/.api_keys

    # construct file
    /usr/bin/awk 'BEGIN {print "Mission,Time"} c&&!--c {printf $0} /# Mission/{c=1} /## Time/ {sum +=$4; print ","$4} END {print ","sum}' $logs/*.journal > $file

    # mail file
    /usr/bin/mailx -a $file -s Timesheet-${currdate} -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp=smtp://smtp.gmail.com:587 -S from="salah.ahmed.hslc@gmail.com(Salah Ahmed)" -S smtp-auth-user=salah.ahmed.hslc@gmail.com -S smtp-auth-password=${GMAIL_PW} -S ssl-verify=ignore -S nss-config-dir=${HOME}/.certs ${to} < /dev/null


    # compress files 
    cd ${logs}
    name=`basename ${file%.*}`
    /usr/bin/zip --quiet ${name}.zip  *.journal
    rm *.journal
fi
