#!/bin/bash
set -u

usage(){
    echo usage
    echo worktree [rm] branch_name
    echo
}

REMOVE=0
if [[ $# -eq 1 ]]; then
    BRANCH=$1
elif [[ $# -eq 2 ]]; then
    if [[ $1 == 'rm' ]]; then
        REMOVE=1
        BRANCH=$2
    else
        usage
        exit
    fi
else
    usage
    exit
fi

git show-ref --verify --quiet refs/heads/$BRANCH
if [[ $? -eq 0 ]]; then
    echo
    echo local branch $BRANCH already exists
    echo
    exit
elif [[ -e /tmp/$BRANCH ]]; then
    echo
    echo directory /tmp/$BRANCH already exists
    echo
    exit
elif [[ $REMOVE -eq 0 ]]; then
    git worktree add -b $BRANCH /tmp/$BRANCH master
else
    git worktree remove /tmp/$BRANCH
fi
