return {
    {"ellisonleao/gruvbox.nvim", priority = 1000, config = true},
    "tpope/vim-surround",
    "tpope/vim-fugitive",
    "ruanyl/vim-gh-line",
    "plasticboy/vim-markdown",
    "godlygeek/tabular",
    "valloric/MatchTagAlways",
    "dag/vim-fish",
    "simnalamburt/vim-mundo",
    "junegunn/fzf.vim",
    "junegunn/fzf",
    "bling/vim-airline",
    "fatih/vim-go",
    "tmhedberg/SimpylFold",
    "Raimondi/delimitMate",
    "majutsushi/tagbar",
    "chase/vim-ansible-yaml",
    "will133/vim-dirdiff",
    "christoomey/vim-tmux-navigator",
    "jnurmine/Zenburn",
    "aklt/plantuml-syntax",
    "scrooloose/vim-slumlord",
    "ctrlpvim/ctrlp.vim",
    "w0rp/ale"
}
